# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

env:
  - CGO_ENABLED=0

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: linux-amd64
    binary: ./vault/plugins/vault-plugin-secrets-kubernetes-reader
    main: ./cmd/vault-plugin-secrets-kubernetes-reader/main.go
    goos:
      - linux
    goarch:
      - amd64

  - id: darwin-amd64
    binary: ./vault/plugins/vault-plugin-secrets-kubernetes-reader
    main: ./cmd/vault-plugin-secrets-kubernetes-reader/main.go
    goos:
      - darwin
    goarch:
      - amd64
  
  - id: darwin-arm64
    binary: ./vault/plugins/vault-plugin-secrets-kubernetes-reader
    main: ./cmd/vault-plugin-secrets-kubernetes-reader/main.go
    goos:
      - darwin
    goarch:
      - arm64

  - id: windows-amd64
    binary: ./vault/plugins/vault-plugin-secrets-kubernetes-reader
    main: ./cmd/vault-plugin-secrets-kubernetes-reader/main.go
    goos:
      - windows
    goarch:
      - amd64
release:
  draft: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^style:'
      - '^refactor:'

dockers:
  - image_templates: 
    - "ghcr.io/revit13/{{.ProjectName}}:latest"
    - "ghcr.io/revit13/{{.ProjectName}}:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
    skip_push: true

