name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  DOCKER_HOSTNAME: ghcr.io
  GO_VERSION: 1.13

jobs:
  build:
    name: Build and push img
    runs-on: ubuntu-latest
    env:
        DOCKER_HOSTNAME: "ghcr.io"
        DOCKER_NAMESPACE: revit13
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-ut-m2-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-ut-m2
    - name: Build
      run: make build
    - id: version
      if: github.event_name != 'pull_request'
      name: Infer version
      run: |
        version="${GITHUB_REF#refs/tags/v}"
        if  [[ $version == refs/* ]] ;
        then
          version='master'
         fi
        echo "DOCKER_TAGNAME=$version" >> $GITHUB_ENV
        echo ::set-output name=push_tag_event::$push_tag_event
    - name: Publish images
      if: github.event_name != 'pull_request'
      run: | 
        make docker-build 
        make docker-push
    - name: Publish latest image tag on push tag event
      if: github.event_name != 'pull_request' && steps.version.outputs.push_tag_event == 'true'
      run: |
        echo "DOCKER_TAGNAME=latset" >> $GITHUB_ENV
        make docker-build
        make docker-push

