name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  DOCKER_HOSTNAME: ghcr.io
  GO_VERSION: 1.13

jobs:
  build:
    name: Build and push img
    runs-on: ubuntu-latest
    env:
        DOCKER_HOSTNAME: "ghcr.io"
        DOCKER_NAMESPACE: revit13
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v2
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
        key: ${{ runner.os }}-ut-m2-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-ut-m2
    - name: Build
      run: make build

